\c saucesource; 

INSERT INTO sauces (name, description, scoville, is_organic, is_kosher, image) VALUES
('Secret Aardvark Habanero', 'A versatile table sauce that adds a special something to near anything. Ingredients include flavorful habanero peppers and roasted tomatoes.', 5000, false, false, 'https://saucesource.netlify.app/images/secret_aardvark.png'),
('Frank''s Red Hot', 'Made with a premium blend of aged cayenne peppers to add a kick of heat and whole lot of flavor to your favorite foods. Bring the heat to wings, chicken sandwiches, buffalo chicken dip, and eggs', 450, false, true, 'https://saucesource.netlify.app/images/franks_red_hot.png'),
('Yellowbird Organic Sriracha', 'Perfectly sweet and spicy, this 100% Organic Sriracha is the first clean condiment of its kind! A rich blend of ripe jalapeños and garlic, finished off with organic dates, so you can feed your addiction without unappetizing additives or added sugars.', 1325, true, false, 'https://saucesource.netlify.app/images/yellowbird_organic_sriracha.png'),
('Tabasco', 'Created by Edmund McIllhenny in 1868, this is a versatile sauce that blends with everything it''s added to, accenting flavors and never masking them. Made from three simple ingredients: red peppers aged in white oak barrels, a small amount of salt and high-quality distilled vinegar.', 400, false, true, 'https://saucesource.netlify.app/images/tabasco.png'),
('Tapatio', 'This sauce is truly a staple for many. It is a blend of herbs and spices that gives your food that spiced you need without feeling guilty. This sauce is free of gluten, sugar and MSG, just pure quality without shortcuts.', 3000, false, true, 'https://saucesource.netlify.app/images/tapatio.png'),
('Valentina Black Label', 'A truly authentic Mexican hot sauce. This spicier version of the yellow-labeled original delivers more than double the heat. ', 2100, false, true, 'https://saucesource.netlify.app/images/valentina_black_label.png'),
('Yellowbird Habanero', 'The perfect pairing for sweet and salty foods. Fresh and bright, this sauce sings with a complex harmony of habanero peppers, garlic, carrots, and tangerine.', 15580, false, false, 'https://saucesource.netlify.app/images/yellowbird_habenaro.png');