\c saucesource; 

INSERT INTO sauces (name, description, scoville, is_organic, is_kosher, link, image) VALUES
('Secret Aardvark Habanero', 'A versatile table sauce that adds a special something to near anything. Ingredients include flavorful habanero peppers and roasted tomatoes.', 5000, false, false, 'https://secretaardvark.com/', 'https://saucesource.netlify.app/bottles/secret_aardvark.png'),
('Frank''s Red Hot', 'Made with a premium blend of aged cayenne peppers to add a kick of heat and whole lot of flavor to your favorite foods. Bring the heat to wings, chicken sandwiches, buffalo chicken dip, and eggs.', 450, false, true, 'https://www.franksredhot.com/', 'https://saucesource.netlify.app/bottles/franks_red_hot.png'),
('Valentina Black Label', 'A truly authentic Mexican hot sauce. This spicier version of the yellow-labeled original delivers more than double the heat. ', 2100, false, true, 'https://salsavalentina.com/', 'https://saucesource.netlify.app/bottles/valentina_black_label.png'),
('Yellowbird Organic Sriracha', 'Perfectly sweet and spicy, this 100% Organic Sriracha is the first clean condiment of its kind! A rich blend of ripe jalapeños and garlic, finished off with organic dates, so you can feed your addiction without unappetizing additives or added sugars.', 1325, true, false, 'https://www.yellowbirdfoods.com/products/organic-sriracha', 'https://saucesource.netlify.app/bottles/yellowbird_organic_sriracha.png'),
('Da Bomb Beyond Insanity', 'The ultimate in hot and way past insanity. Pure habanero pepper enhanced with habanero-infused flavor create a sauce wicked beyond belief! Made in Kansas, this sauce is said to be "the hot sauce that everyone loves to hate". As seen on the First We Feast series "Hot Ones."', 135600, false, false, 'https://www.spicinfoods.com/da-bomb-beyond-insanity-hot-sauce.html', 'https://saucesource.netlify.app/bottles/da_bomb_beyond_insanity.png'),
('Huy Fong Sriracha', 'Created from sun ripened chilies pureed into a smooth paste, this sauce can be recognized by its bright red color and its distinctive packaging: a clear plastic bottle with rooster on its label and a green cap. Sriracha is made from fresh, red, jalapeño chili peppers. Great to use in soups, sauces, pasta, pizza, hot dogs, hamburgers, chow mien or on anything to add a delicious, spicy taste.', 2200, false, true, 'https://www.huyfong.com/', 'https://saucesource.netlify.app/bottles/huy_fong_sriracha.png'),
('Tabasco', 'Created by Edmund McIllhenny in 1868, this is a versatile sauce that blends with everything it''s added to, accenting flavors and never masking them. Made from three simple ingredients: red peppers aged in white oak barrels, a small amount of salt and high-quality distilled vinegar.', 400, false, true, 'https://www.tabasco.com/', 'https://saucesource.netlify.app/bottles/tabasco.png'),
('Pain Is Good Habanero', 'Looking for a kick of heat? This habanero hot sauce is made in Kansas City by Pain is Good. Blended with carrots, mustard and garlic to balance the flavor of bold and spicy habanero peppers. The result is a delicious, fiery hot sauce that you''ll want to serve with every meal.', 9410, false, false, 'https://www.hotsauce.com/most-wanted-pain-is-good-habanero-hot-sauce/', 'https://saucesource.netlify.app/bottles/pain_is_good.png'),
('Tapatio', 'This sauce is truly a staple for many. It is a blend of herbs and spices that gives your food that spiced you need without feeling guilty. This sauce is free of gluten, sugar and MSG, just pure quality without shortcuts.', 3000, false, true, 'https://www.tapatiohotsauce.com/', 'https://saucesource.netlify.app/bottles/tapatio.png'),
('Yellowbird Habanero', 'The perfect pairing for sweet and salty foods. Fresh and bright, this sauce sings with a complex harmony of habanero peppers, garlic, carrots, and tangerine.', 15580, false, false, 'https://www.yellowbirdfoods.com/products/classic-habanero-hot-sauce', 'https://saucesource.netlify.app/bottles/yellowbird_habenaro.png'),
('Mad Dog 357', 'Be prepared to shiver in fear. This sauce is one of the most powerful sauces in the world, and it will take your breath away with its 357,000 Scoville Heat Units. One hit will blow you away! Don''t even think you can handle this heat gracefully. With a blend of 160,000 SHU Cayenne peppers, fiery hot red Habanero peppers, and a whopping 3,000,000 Scoville pepper extract will provide a tantalizing tingle from your tongue to your toes.', 357000, false, false, 'https://maddog357.com/collections/our-products/products/3571', 'https://saucesource.netlify.app/bottles/mad_dog_357.png'),
('Blair''s Mega Death Sauce', 'This sauce is devilishly hot. Merciless heat and maximum flavour meet to bring a truly spectacular sweat to your heat-seeking brow. Molasses momentarily masks the hard-hitting habanero, cayenne, and chipotle chilli that make up this menacing mix. Feel alive with Blair''s Mega Death, and endure its painful pleasure one daring drop at a time. Use sparingly. Not recommended for use without dilution.', 550000, false, false, 'https://deathsauce.com/shop/mega-death-sauce/', 'https://saucesource.netlify.app/bottles/blairs_mega_death_sauce.png'),
('Crystal', 'A Louisiana favorite, made with fresh ground cayenne peppers. The controlled heat level keeps the accent on flavor. This sauce has a prominent dark chile flavor, and a slightly subdued vinegar profile.', 4000, false, true, 'https://crystalhotsauce.com/product/crystal-hot-sauce/', 'https://saucesource.netlify.app/bottles/crystal.png'),
('El Yucateco Green Habanero', 'Made with the freshest green habanero peppers, garlic and fine spices blend into a fresh, flavorful sauce. The full, rich consistency and savory flavor of this sauce satisfies even the most discriminating palate to spice up any kind of meat, salad, or recipe.', 9000, false, true, 'https://www.shopelyucateco.com/', 'https://saucesource.netlify.app/bottles/el_yucateco_green_habanero.png'),
('Texas Pete', 'This sauce adds epic flavor to just about any food, without smothering it with heat. Made with a time-tested secret blend of specially-selected peppers that have been fermented to perfection, it wrangles up a bold and balanced flavor for the ultimate picante medley. A famous blend of 3 different types of peppers are aged to perfection and bring out the natural, bold flavor. The result is a rich, delicious sauce with strong cayenne overtones. Great to spice up barbecue, eggs, pizza, chicken, veggies, and just about everything else.', 750, false, true, 'https://texaspete.com/shop/', 'https://saucesource.netlify.app/bottles/texas_pete.png');